### ISSUE TITLE
Page view: some weird visual artifact

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#15]
![screen shot 2016-07-29 at 11 27 10 am](https://cloud.githubusercontent.com/assets/284315/17255574/70512f5c-557f-11e6-9a30-4f63a824200d.png)

some weird artifact int he control bar

**Comment by jduss4** [comment]
Most of the code for the `item-ctrl` seems to be older code which doesn't affect the current view beyond the first two lines for the background and border.  I'm removing it for now in order to make the display a tad better:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/2480492/50351190-05b26c80-0507-11e9-9b65-3ddb6861d701.png">

https://github.com/CDRH/open-oni_nebraska_theme/blob/master/static/css/main.scss#L264

@karindalziel recommends leaving her an issue to fix the spacing at the top of the + - bits on the left rather than me spending time on it.  Closing this issue and opening another once code is committed.
