### ISSUE TITLE
"similar issues for date" problem with Pokrok Zapadu and Omaha Daily Bee

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#31]
For dates on which issues of both the Omaha Daily Bee and Pokrok Zapadu are published, "similar issues for date" are displaying at the bottom of the page, when viewing individual page images. For example, when viewing the Bee of 4 December 1912, links to every page of the Pokrok Zapadu issue for that same date are listed at the bottom of the page under the head "similar issues for date," and vice versa. Other titles appeared on this date (Daily Nebraskan & Wilberske listy), but neither of these titles appear to be linked to the Bee and Pokrok Zapadu in this way.

Links to "similar issues for date" don't display elsewhere in Nebraska Newspapers, from what I can tell, and I'm not sure why it's happening here. Once we figure out what is going on, perhaps disabling/hiding that feature for these two titles is the way to go.

http://nebnewspapers.unl.edu/lccn/sn99021999/1912-12-04/ed-1/seq-1/
http://nebnewspapers.unl.edu/lccn/sn83045348/1912-12-04/ed-1/seq-1/

**Comment by jduss4** [comment]
Depending on what @karindalziel finds, it seems like we have a couple routes:

Nebraska Only:
- hide the feature from the UI if we aren't using it but leave it in the backend
- only show the first page of an issue instead of all the pages

Open ONI Changes:
- expand the feature so that it's across all cities on a particular date (and improve UI to be issues instead of pages)
- simply improve the UI for base Open ONI install (issues instead of pages)
- completely remove the feature

**Comment by karindalziel** [comment]
oh shoot is this up to me?

Unless @jnlsmns or @lweakly think this is a good feature, I'd say just turn it off locally. For Oni, let's make an issue over there.

**Comment by jnlsmns** [comment]
I think the feature is a good one, but don't like the way it's implemented at the moment. Considering the possibilities that Jessica lists above, I think I like the idea of expanding the feature so that it's across all cities on a particular date and listing the relevant issues for that day, instead of individual pages

**Comment by jduss4** [comment]
I vote because of time restrictions we're running up against this sprint that we simply hide it for now in our templates and move this issue to the next sprint.

**Comment by jduss4** [comment]
This is in nebnews but the functionality does not appear to exist in Open ONI anymore at all.  I can't tell when it would have been removed so perhaps it was never in Open ONI having not made the jump from the LoC theme in chronam?  There is still a relic in the view providing the related pages which I am removing.  If we WANT a related pages then we can certainly recreate it without too much hassle, but it seems that it's not a particularly desired feature so I'm closing this issue for now.
