### ISSUE TITLE
Eiseley batch errors

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#32]
Problem 1: Some images don't display
Problem 2: We need to separate out Hemingford Herald into a separate batch
Problem 3: The dates of red cloud chief are incorrect

**Comment by karindalziel** [comment]
Some more info from https://github.com/CDRH/nebnews/issues/45

- A non working page: http://nebnewspapers.unl.edu/lccn/2010270501/1895-07-26/ed-1/seq-1/

Comment from Jess: 

```
Note, there is an existing problem for this batch reported in the tracking spreadsheet

"Had to arrange the documents from three different places and change the lccns in hundreds of documents before I could finally get this to work. And then it turns out the LoC doesn't have an lccn for Hemingford Heralds -- it thinks that they are the Alliance Herald ahhhhhhh"
```

**Comment by jnlsmns** [comment]
problem 1: some images don't display
jp2 image files associated with reels 00237285074 (contains Hemingford herald and Alliance herald issues) and 00237285098 (contains Alliance herald issues only) are not loading in Nebraska Newspapers; however, the files appear to be loading in Chronicling America without any problems. It seems that the jp2 files being served in nebnews are corrupt in some way--when trying to open them in Photoshop, the following error occurs: "Could not complete your request because the file-format module could not parse the file." In talking with Jessica and Karin, it seems as if the best course of action is to download the batch from Chronicling America and re-ingest it into nebnews so that our batch reflects the batch as it exists in ChronAm. Currently, however, the nebnews iteration of batch_nbu_eisley is not the same as the iteration in ChronAm--our batch_nbu_eisley includes additional issues that do not appear in ChronAm and that we want to keep in nebnews. A discrepancy which leads to both problems 2 & 3.

problem 2: separate Hemingford herald into a separate batch
The Hemingford herald (from 1895-07-26 through 1898-08-26) should be removed from batch_nbu_eisley.  As is stands now, the xml files for this title are valid; however, the jp2 and pdf files associated with the Hemingford herald produce verification errors in the DVV. The metadata embedded in the headers for these image files is incorrect. At the time of digitization, metadata for the Alliance herald was assigned to the images of the Hemingford paper. Ideally, we'd like to change this metadata to reflect the appropriate information, but we might be able to ingest the batch into nebnews and have it function with the current, incorrect metadata. The screenshot below captures from the DVV the header information that needs to be changed for each jp2 and pdf file for this title. 
![dvv--header_metadata_view](https://user-images.githubusercontent.com/38263772/44360250-e97ec000-a47f-11e8-9092-4a182d6da1ea.jpg)
* in the title field, "The Alliance Herald. (Alliance, NE)" should be replaced with "Hemingford herald. (Hemingford, Box Butte County, Neb.)"
* in the description field, "The Alliance Herald" should be replaced with "Hemingford herald" and "sn2010270501" should be replaced with "2010270501"
N.B.--The Hemingford herald issues are not in Chronicling America, and thus, we will not be able to download image files with the correct metadata for this title. If we cannot manipulate the metadata for the existing files, and the images with the incorrect metadata won't work in nebnews, this portion of reel 00237285074 might require re-work. 

problem 3: date of the Red Cloud chief
We will also need to extract from batch_nbu_eisley the last year of the Red Cloud chief as it was published post 1922 and is not in ChronAm. All 1923 issues of the Red Cloud chief should be included in nebnews in a separate batch or as part of the batch that contains the Hemingford herald issues, for which the inclusive dates are as follows: 1923-01-04 through 1923-11-22.

I have created a separate batch for all Hemingford herald issues, batch_nbu_eiseleyextras, and will add the 1923 Red Cloud chief to that batch as well. We can always change the batch name, if needed.

**Comment by jnlsmns** [comment]
1: @jduss4 download eiseley batch from loc
2: @jnlsmns will save our eiseley batch for reference
3: @jduss4 will copy tiffs in and generate list of discrepancies between our batch and loc's batch
4: @jnlsmns create a new batch with "eiseley extras"

**Comment by jduss4** [comment]
I'll hold off on copying in tiffs until we find out if Janel's eisley batch with the other things removed matches the one that LoC has!

**Comment by jnlsmns** [comment]
Jessica, let's double-check this Monday (if you're in then), but I think the batch on the U drive should now reflect the batch as it is in chronicling america!

**Comment by jnlsmns** [comment]
i removed the eiseley_extras directory from the eisley batch and moved the 1923 issues of the Red Cloud chief into batch_nbu_meadowanemone

**Comment by jduss4** [comment]
I compared a version of eisley from the LoC and the batch that Janel recreated, and other than tiffs, the file structure is the same!  Whoo hoo

**Comment by jduss4** [comment]
Note for the future: just make sure we use eisley batch from U drive in the future instead of eisley on old newspaper server!!!
