### ISSUE TITLE
Issues/Pages with no image can't be linked to

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#33]
(This issue was moved from CDRH_General)

See, for instance, the Hesparian: http://nebnewspapers.unl.edu/lccn/sn96080316/issues/first_pages/

The link says "No image" but it should click through to a page like this: http://nebnewspapers.unl.edu/lccn/sn96080316/1872-01-01/ed-1/

@jnlsmns will look for an example of how this functions on chronam

@jduss4 added: Not sure why the link wouldn't be working, but investigate what the highlight URL looks like:

https://github.com/CDRH/nebnews/blob/master/nebraska/templates/search_pages_results.html#L138

Ideally, I think this should show a graphic that says "This issue has no available digitized pages" or "Image not available" (with appropriate attributes added for screenreaders) with the date below.

**Comment by jnlsmns** [comment]
In Chronicling America, missing page images display as follows: 
![chronam_missing_image](https://user-images.githubusercontent.com/38263772/44363792-d32a3180-a48a-11e8-81cb-ebdb7f5c0b22.jpg)

The associated code is as follows:
`<dmdSec ID="pageModsBib3"><mdWrap LABEL="Page metadata" MDTYPE="MODS"><xmlData><MODS:mods><MODS:part><MODS:extent unit="pages"><MODS:start>3</MODS:start></MODS:extent><MODS:extent unit="page number"><MODS:start>3</MODS:start></MODS:extent></MODS:part><MODS:relatedItem type="original"><MODS:identifier type="reel number">00100478432</MODS:identifier><MODS:location><MODS:physicalLocation authority="marcorg" displayLabel="California State Library, Sacramento, CA">C</MODS:physicalLocation></MODS:location></MODS:relatedItem><MODS:note displayLabel="University of California, Riverside" type="agencyResponsibleForReproduction">CU-Riv</MODS:note><MODS:note displayLabel="missing page" type="noteAboutReproduction">Not digitized, published</MODS:note></MODS:mods></xmlData></mdWrap></dmdSec>`

**Comment by karindalziel** [comment]
I'm not clear on exactly what the next steps are on this one, need to discuss.

**Comment by jduss4** [comment]
I believe the next steps are that me and Greg need to build a landing page / link for these, possibly in Open ONI because it seems like a feature they will probably want as well

**Comment by jduss4** [comment]
This is where the URL is created in open-oni:  https://github.com/open-oni/open-oni/blob/d54df9a82c86ddeb34e2e97048a6bdba2bb2388b/core/templates/issue_pages.html#L35

Our URLs are empty in nebnews which is why it goes back to the current page.  I'm guessing that means that metadata about the missing images / issues in question is not quite recognizable for the open oni software?

For future reference, bravo has:
`sn96080316/00000000007/1872010101/1872010101.xml` : `<mods:note type="noteAboutReproduction">Not digitized, published</mods:note>`

**Comment by jduss4** [comment]
Fortunately, we do have a page that will display for that particular page:  http://nebnewspapers.unl.edu/lccn/sn99021999/1920-04-02/ed-1/

The question is, why isn't our site building the URL?  Is it something to do with the metadata / storing it in the database?

**Comment by jduss4** [comment]
Okay, there are TWO separate issues:

Front page display where an entire ISSUE is missing (this doesn't even work in LoC)
https://chroniclingamerica.loc.gov/lccn/sn99021999/issues/first_pages/722/

Page within an issue where only one / some pages are missing (haven't tested if this works in open oni but works in chronam):
https://chroniclingamerica.loc.gov/lccn/2017270205/1899-09-28/ed-1/

So we specifically need to address only that first one, when an entire issue is missing.  The URL isn't being populated so I'll look into that, first, because the page does exist it just isn't being linked to.  @jnlsmns recommends a temp solution, otherwise, which is that since it looks like a link it is confusing when it doesn't work, so perhaps we should just make it NOT a link.  This would be pretty easy to do in the `issue_pages` template I believe.

**Comment by jduss4** [comment]
I think I'm going to split this into several issues, now that more information about them has been identified.  In the case of bravo's Hesperian Student, specifically, the front pages of issues are being returned as `None` so there's no date information to retrieve from them, etc.  I think I will need to create a miniature batch and inspect how the information is being ingested into the database before I can get much more information from that.

**Comment by jduss4** [comment]
Holding off on splitting this into issues until returning to nab existing issues after the launch of the openoni.  There's a batch on the dev server called bravoMini which has `1871100101` and `1872010101` in it.  If you load it, you'll see the batch description has "2 issues, 4 pages" but it doesn't have any links to the 1872 issue at all, only the 1871 issue...
