### ISSUE TITLE
fix title ingest

### ISSUE THREAD

**Issue by jnlsmns** [CDRH/open-oni_nebraska_theme#38]
#37 

![image](https://user-images.githubusercontent.com/38263772/48635209-24b06280-e98d-11e8-8963-e021ebceff62.png)

regularize titles so that they don't pull in format designations, such as "microform" and "volume"

**Comment by jduss4** [comment]
alternatively we can leave the titles in the database as they normally load but just cut those labels off in the templates

**Comment by karindalziel** [comment]
I can't remember if we made a final decision about this, may still need to discuss

**Comment by jduss4** [comment]
I think that this is where the volume / microform type label is coming from:  https://github.com/open-oni/open-oni/blob/dev/core/models.py#L243

it's possible that we might be able to override the model's properties somewhere in our app to make the display name just the title.  Otherwise I don't think that changing the ingest script will help particularly?  I'll keep looking into this a bit.

**Comment by jduss4** [comment]
I should mention that we could also just override the newspapers table view to use "name" instead of "display name" as well

**Comment by jduss4** [comment]
I am inquiring about whether open oni folks want the medium in their display.  If not, I wonder if perhaps it wouldn't just be easier to add a configuration setting so that people can easily toggle the volume / microform label on or off for their installation.

**Comment by jduss4** [comment]
addressed by https://github.com/open-oni/open-oni/pull/369
