### ISSUE TITLE
Issue view

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#79]
- [x] Issue view: Change "Omaha Daily Bee main page to "about omaha daily bee" see https://nebnewspapers-dev.unl.edu/lccn/sn99021999/1895-03-18/ed-1/)
- [x] Issue view: it's confusing that "first issue" and "last issue" take one to a page, rather than an issue view. Consider removing (Karin discuss with Laura/Janel)

**Comment by jduss4** [comment]
I've started working on this issue and I'm not sure if you want the links to look the same way that they used to?  For now I put the "About Omaha Daily Bee" link in the openoni design so it's a button instead of just a text link.

Also, I changed the "first issue" and "last issue" links so that they will link to the overview of an issue instead of to a specific page.
