### ISSUE TITLE
Newspaper Page changes

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#8]
Not sure if we should totally overwrite this template from Core or not. 

Changes include:
- Added explanatory text + link to newspaper directory at the top
- different columns. Karin had an idea to change these columns for core, see https://github.com/open-oni/open-oni/issues/206
- If we want to make open-oni live on Nebraska servers before we do the above, we should at least change state to city

**Comment by jduss4** [comment]
related to https://github.com/CDRH/open-oni_nebraska_theme/issues/20
I think we should wait on those more dramatic column changes, especially because it seems to be paired with some of the filtering functionality.

"State" no longer appears (neither does city) but we do have "Location"

I'm going to close this issue for now and we can revisit later when we work on the newspapers filtering
